import React from 'react';

export const Home = () => (
<div>
    <h2>Hello World</h2>
    <p>­From those humble origins, Formula One racing was born, and over the years, it has grown to be one of the most popular sports in the world. It appeals to millions of fans, attracts a huge sponsorship and delivers champions who are as revered as Olympic medalists. Why? Because Formula One racing satisfies our fundamental need ­to push technology to its limits and to enjoy, even if vicariously, the thrill and excitement of high-speed travel.</p>
    <p>Formula One (also known as Formula 1 or F1) is the highest class of single-seater auto racing sanctioned by the Fédération Internationale de l'Automobile (FIA) and owned by the Formula One Group. The World Drivers' Championship, which became the FIA Formula One World Championship in 1981, has been one of the premier forms of racing around the world since its inaugural season in 1950. The word "formula" in the name refers to the set of rules to which all participants' cars must conform.[1] A Formula One season consists of a series of races, known as Grands Prix (French for ''grand prizes' or 'great prizes''), which take place worldwide on purpose-built circuits and on public roads.</p>
    <p>The results of each race are evaluated using a points system to determine two annual World Championships: one for drivers, the other for constructors. Drivers must hold valid Super Licences, the highest class of racing licence issued by the FIA.[2] The races must run on tracks graded "1" (formerly "A"), the highest grade-rating issued by the FIA.[2] Most events occur in rural locations on purpose-built tracks, but several events take place on city streets.</p>
    <p>Formula One cars are the fastest regulated road-course racing cars in the world, owing to very high cornering speeds achieved through the generation of large amounts of aerodynamic downforce. The cars underwent major changes in 2017,[3] allowing wider front and rear wings, and wider tyres, resulting in peak cornering forces near 6.5 lateral g and top speeds of up to approximately 350 km/h (215 mph).[4][5] As of 2019 the hybrid engines are limited in performance to a maximum of 15,000 rpm, the cars are very dependent on electronics and aerodynamics, suspension and tyres. Traction control and other driving aids have been banned since 2008</p>
    <p>While Europe is the sport's traditional base, the championship operates globally, with 11 of the 21 races in the 2019 season taking place outside Europe. With the annual cost of running a mid-tier team—designing, building, and maintaining cars, pay, transport—being US$120 million,[7] its financial and political battles are widely reported. Its high profile and popularity have created a major merchandising environment, which has resulted in large investments from sponsors and budgets (in the hundreds of millions for the constructors). On 23 January 2017 Liberty Media confirmed the completion of the acquisition of Delta Topco, the company that controls Formula One, from private-equity firm CVC Capital Partners for $8 billion.</p>
    <p>A budget cap is set to be introduced for each Formula One team, starting in the 2021 season, so as to ensure fair competition and sustainable development of the sport. The amount of the budget cap is set to be $175 million, however due to the current coronavirus pandemic some have argued the amount should be lowered.</p>
</div>

)